In [6]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
df = pd.read_csv('smart_manufacturing_data.csv',parse_dates=['timestamp'])
print("Shape:",df.shape)
df.head()

Shape: (100000, 13)

,timestamp,machine_id,temperature,vibration,humidity,pressure,energy_consumption,machine_status,anomaly_flag,predicted_remaining_life,failure_type,downtime_risk,maintenance_required
0,2025-01-01 00:00:00,39,78.61,28.65,79.96,3.73,2.16,1,0,106,Normal,0.0,0
1,2025-01-01 00:01:00,29,68.19,57.28,35.94,3.64,0.69,1,0,320,Normal,0.0,0
2,2025-01-01 00:02:00,15,98.94,50.20,72.06,1.00,2.49,1,1,19,Normal,1.0,1
3,2025-01-01 00:03:00,43,90.91,37.65,30.34,3.15,4.96,1,1,10,Normal,1.0,1
4,2025-01-01 00:04:00,8,72.32,40.69,56.71,2.68,0.63,2,0,65,Vibration Issue,0.0,1

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 13 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   timestamp                 100000 non-null  datetime64[ns]
 1   machine_id                100000 non-null  int64
 2   temperature               100000 non-null  float64
 3   vibration                 100000 non-null  float64
 4   humidity                  100000 non-null  float64
 5   pressure                  100000 non-null  float64
 6   energy_consumption        100000 non-null  float64
 7   machine_status            100000 non-null  int64
 8   anomaly_flag              100000 non-null  int64
 9   predicted_remaining_life  100000 non-null  int64
 10  failure_type              100000 non-null  object
 11  downtime_risk             100000 non-null  float64
 12  maintenance_required      100000 non-null  int64
dtypes: datetime64[ns](1), float64(6), int64(5), object(1)
memory usage: 9.9+ MB

In [8]:
df.describe(include='all').T

,count,unique,top,freq,mean,min,25%,50%,75%,max,std
timestamp,100000,NaN,NaN,NaN,2025-02-04 17:19:29.999999744,2025-01-01 00:00:00,2025-01-18 08:39:45,2025-02-04 17:19:30,2025-02-22 01:59:15,2025-03-11 10:39:00,NaN
machine_id,100000.0,NaN,NaN,NaN,25.49933,1.0,13.0,25.0,38.0,50.0,14.389439
temperature,100000.0,NaN,NaN,NaN,75.015625,35.55,68.2675,75.06,81.75,121.94,10.031884
vibration,100000.0,NaN,NaN,NaN,50.01227,-17.09,39.97,49.96,60.1,113.8,14.985444
humidity,100000.0,NaN,NaN,NaN,54.995401,30.0,42.52,54.98,67.5,80.0,14.43796
pressure,100000.0,NaN,NaN,NaN,3.000405,1.0,2.0,3.01,4.0,5.0,1.152399
energy_consumption,100000.0,NaN,NaN,NaN,2.747064,0.5,1.63,2.74,3.87,5.0,1.297865
machine_status,100000.0,NaN,NaN,NaN,1.00205,0.0,1.0,1.0,1.0,2.0,0.446193
anomaly_flag,100000.0,NaN,NaN,NaN,0.08916,0.0,0.0,0.0,0.0,1.0,0.284976
predicted_remaining_life,100000.0,NaN,NaN,NaN,234.26916,1.0,97.0,230.0,365.0,499.0,150.063062
failure_type,100000,5,Normal,91899,NaN,NaN,NaN,NaN,NaN,NaN,NaN
downtime_risk,100000.0,NaN,NaN,NaN,0.089155,0.0,0.0,0.0,0.0,1.0,0.284961
maintenance_required,100000.0,NaN,NaN,NaN,0.19697,0.0,0.0,0.0,0.0,1.0,0.397711